### PR TITLE
Fixed Openshift Pentest section broken/missing links

### PR DESCRIPTION
**Pull request by Tochirou**
Very small PR which adds small tweaks to fix broken link on the openshift - jenkins subsection and author links.

### CODE REVIEW

**Comment by carlospolop** [comment]
Thanks @Tochirou !

**Comment by Tochirou** [comment]
erf sorry i'm no expert with gitbook page indexing, seems like the link to openshift-jenkins-build-overrides.md in the jenkins subsection page is still broken :(

**Comment by carlospolop** [comment]
Fixed:) No worries @Tochirou, let me know if you find any other issue, and feel free to update this section whenever you guys find more interesting attacks

**Comment by Tochirou** [comment]
Thanks a lot! We won't hesitate :)

**Pull request merged**
